#App configuration
framework:
    locale: en
    session: ~
    
# Orm Configuration
orm:
    database:
        driver:     mysql
        host:       localhost
        port:       ~
        dbname:     phady
        username:   root
        password:   dani
        charset:    UTF8
