--- # System routes
routes:
    - path:       /login
      options:
        module:     common
        namespace:  App\Common\Controllers
        controller: login
        action:     login

    - path:       /login_check
      options:
        module:     common
        namespace:  App\Common\Controllers
        controller: login
        action:     login_check

    - path:       /logout
      options:
        module:     common
        namespace:  App\Common\Controllers
        controller: login
        action:     logout

    - path:       /access_denied
      options:
        module:     common
        namespace:  App\Common\Controllers
        controller: login
        action:     access_denied